import "./globals.css";
import type { Metadata } from "next";

import Navbar from "@/components/navbar";
import { WalletProvider } from "@/contexts/WalletProvide";
import { ApolloProvider, ApolloClient, InMemoryCache } from "@apollo/client";
import { Apolloprovider } from "@/apolloProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased `}
      >
        <Apolloprovider>
          <WalletProvider>
            <Navbar />
            {children}
          </WalletProvider>
        </Apolloprovider>
      </body>
    </html>
  );
}
