import "./globals.css";
import type { Metadata } from "next";

import Navbar from "@/components/navbar";
import { WalletProvider } from "@/contexts/WalletProvide";
import { Apolloprovider } from "@/apolloProvider";
import { Provider } from "./provider";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased `}
      >
        <Provider>
          <WalletProvider>
            <Apolloprovider>
              {children}
            </Apolloprovider>
          </WalletProvider>
        </Provider>
      </body>
    </html>
  );
}
